version: '3.3'
services:
    # ------> postgre ------>
    db:
      container_name: 'postgres'
      image: postgres
      ports:
        - "5433:5433"
        # (HOST:CONTAINER)
      environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: smart
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
    # <------ postgre <------
    # ------> app ------>
    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      restart: always
      volumes:
        - .:/app
        # (HOST:CONTAINER)
      ports:
        - "8001:8000"
        # (HOST:CONTAINER)
      depends_on:
        - db
        - scrapyd
    # <------ app <------
    # ------> adminer ------>
    adminer:
      container_name: adminer
      image: adminer:latest
      restart: always
      environment:
        ADMINER_PLUGINS: tables-filter tinymce
        ADMINER_DESIGN: pepa-linha
      ports:
        - 8080:8080
      depends_on:
        - db
    # <------ adminer <------
    reactapollo:
      container_name: reactapollo
      build: ./react
      ports:
        - "3001:3000"
      volumes:
        - type: bind
          source: ./react/src
          target: /app/src
        - type: bind
          source: ./react/public
          target: /app/public
        # (HOST:CONTAINER)
      command: npm start
      restart: always
      depends_on:
        - web

    scrapyd:
      container_name: scrapyd
      build: .
      command: scrapyd
      working_dir: /app/crawler
      restart: always
      ports:
        - "6800:6800"
      volumes:
        - .:/app 
      depends_on:
        - db

volumes:
    postgres_data:
