# Generated by Django 2.2.2 on 2019-06-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetitle', models.CharField(max_length=50, unique=True)),
                ('casetitle_long', models.CharField(max_length=250, unique=True)),
                ('arbitration_rules', models.TextField(blank=True, max_length=50, null=True)),
                ('decisions_rendered', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
