# Generated by Django 2.2.2 on 2019-06-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='arbitration_rules',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='decisions_rendered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
