# Generated by Django 2.2.2 on 2019-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20190628_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
